apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: upgrade-input
  namespace: plumber-kafka
  labels:
    strimzi.io/cluster: plumber-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: upgrade-output
  namespace: plumber-kafka
  labels:
    strimzi.io/cluster: plumber-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
