apiVersion: plumber.ugent.be/v1alpha1
kind: TopologyPart
metadata:
  name: my-first-topo-scientist
spec:
  processors:
    transformer-0:
      inputFrom: kafka-ingress
      image: "verstraetebert/plumber-greeter:v0.0.1"
      env:
        - name: MSG
          value: "Hello from transformer-0!"
      maxScale: 8
    transformer-1:
      inputFrom: transformer-0
      image: "verstraetebert/plumber-greeter:v0.0.1"
      env:
        - name: MSG
          value: "Hello from transformer-1!"
      sinkBindings: kafka-egress
      maxScale: 24
